# Generated by Django 3.0.5 on 2020-05-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200526_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='dead_line',
            new_name='deadline',
        ),
    ]
