# Generated by Django 3.0.6 on 2020-05-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200529_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created_date',)},
        ),
    ]
