# Generated by Django 3.0.6 on 2020-05-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200529_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'created_date']},
        ),
    ]
