# Generated by Django 3.0.6 on 2020-05-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200529_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_date', 'deadline']},
        ),
    ]
